BS-151 | Bulk FHIR export of Anonymised Patient Data from Bahmni (Redact)
Bahmni/openmrs-module-fhir2Extension pull request #30
Opened 2023-07-31 13:57 UTC by manimaarans

## Requirements

- [x] This PR has a proper title that briefly describes the work done
- [x] I have squashed / amended the comments to make it more redable
- [x] I have included link to all the JIRA ticket('s)
- [x] I wrote the code as a pair or atleast performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Summary

## Screenshots

## JIRA tickets

https://bahmni.atlassian.net/browse/BS-151

## Other

2023-07-31 14:06 UTC, gsluthra requested changes

2023-07-31 14:06 UTC, gsluthra commented on omod/src/main/resources/config.xml
> +		<description>Ability to export non anonymised patient data in FHIR format</description>
Ability to bulk-export patient data that has NOT been anonymised, in FHIR JSON format.

2023-07-31 14:06 UTC, gsluthra commented on omod/src/main/resources/config.xml
> +		<description>Properties file path for fhir export anonymisation</description>
Path of the config file that controls the anonymisation mechanism during bulk-export of patient data.

2023-08-01 05:18 UTC, vijayanandtwks commented on api/src/main/java/org/openmrs/module/fhirExtension/export/impl/PatientExport.java
> +	private List<IBaseResource> anonymise(List<IBaseResource> iBaseResources) {
All implementations of Exporter have this redundant method 
List<IBaseResource> anonymise(List<IBaseResource> iBaseResources)
Add additional parameter i.e. resource type and move it to default method in the interface

2023-08-01 05:22 UTC, vijayanandtwks commented on api/src/main/java/org/openmrs/module/fhirExtension/export/anonymise/config/AnonymisedResourceConfig.java
> +public class AnonymisedResourceConfig {
Naming not consistent - anonymised, anonymiser, anonymise. Use only one style

2023-08-02 05:50 UTC, gsluthra commented
OK from my side. thanks.

2023-08-02 05:50 UTC, gsluthra approved these changes

2023-08-02 06:00 UTC, vijayanandtwks approved these changes

2023-08-02 06:14 UTC, merged